baseURL = "http://www.tarunjana.in/"
title = "Tarun Jana"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

publishDir = "docs"

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "tarun-kumar-jana"

[params]
    author = "Tarun Jana"
    description = "A Place For Me & My Alter Ego"
    keywords = "blog, developer, coder, personal"
    info = "A Passionate Coder"
    avatarURL = "images/Tarun-Jana.jpg"
    favicon_32 = "images/favicon/favicon-32x32.png"
    favicon_16 = "images/favicon/favicon-16x16.png"
    touchIcon = "images/favicon/apple-touch-icon.png"
    footerContent = "All Rights Reserved"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2021

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = false

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "tarunjana"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/tarunjana/"
[[params.social]]
    name = "Dev.To"
    icon = "fa fa-dev-to"
    weight = 2
    url = "https://dev.to/tarunjana/"
[[params.social]]
    name = "Facebook"
    icon = "fa fa-facebook-official"
    weight = 3
    url = "https://www.facebook.com/TheTarunJana/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 4
    url = "https://twitter.com/TheTarunJana/"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 3
            url = "contact/"

            [[languages.en.menu.main]]
            name = "Tags"
            weight = 4
            url = "tags/"